spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: false


    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/changelog.xml