spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.cache.use_second_level_cache: true
      hibernate:
        format_sql: false


    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/changelog.xml