version: "3.3"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "dynamic_store"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"